variables:
  ENABLE_GATLING: 'false'
  ENABLE_KARATE: 'true'
  ENV: 'QUA'
  DEBUG: "1"
  GLOBAL_PROXY: ${GLOBAL_PROXY}

############### RUNNER TAGS ###############

.tags_rlt: &tags_rlt
  tags:
    - rlt
    - aws
    - build
    - docker

stages:
  - get-features
  - functional-tests
  - load-tests
  - send-report

############# LOAD TEST ###############
get-features:
  <<: *tags_rlt
  image: node:10-alpine
  stage: get-features
  variables:
    JIRA_XRAY_HOST: jira.dt.renault.com
    XC_DEFAULT_TEST_PLAN: $TEST_PLAN_JIRA_KEY
    XC_USE_XRAY_FEATURE_FILES: "true"
    XC_FEATURES_DOWNLOAD_DIRECTORY: "../../src/test/java/com/renault"
    XC_TEST_PLAN_FILE: "../../src/test/java/test-plan.json"
  script:
    - apk add -Uuv curl
    - rm -fr ${XC_FEATURES_DOWNLOAD_DIRECTORY}/ACTIVE
    - cd tools/xray-connector
    - curl -u${ARTIFACTORY_USER}:${ARTIFACTORY_TOKEN} "https://artifactory.dt.renault.com/artifactory/api/npm/npm-renault/auth/rd" > .npmrc
    - npm install
    - npm run xc:get-features
  artifacts:
    when: always
    expire_in: 12 hrs
    paths:
      - src/test/java/com/renault/ACTIVE
      - src/test/java/test-plan.json
  rules:
    - if: '$CI_PIPELINE_SOURCE == "schedule" || $CI_PIPELINE_SOURCE == "pipeline"'
      when: always
    - if: '$CI_PIPELINE_SOURCE != "schedule" && $CI_PIPELINE_SOURCE != "pipeline"'
      when: manual

functional-tests:
  <<: *tags_rlt
  image: adoptopenjdk:11-jdk-openj9-bionic
  stage: functional-tests
  allow_failure: true
  variables:
    http_proxy: "http://${PROXY_HOST}:${PROXY_PORT}"
    https_proxy: "http://${PROXY_HOST}:${PROXY_PORT}"
    no_proxy: "127.0.0.1,localhost"
    GRADLE_OPTS: "-Dhttp.proxyHost=${PROXY_HOST} -Dhttp.proxyPort=${PROXY_PORT} -Dhttps.proxyHost=${PROXY_HOST} -Dhttps.proxyPort=${PROXY_PORT} -DnonProxyHosts=${no_proxy}"
  script:
    - source config/api-env/Common
    - ./gradlew --no-daemon test --tests AllApiTestsRunner -Dkarate.env=$ENV
  artifacts:
    expire_in: 12 hrs
    paths:
      - build
    when: always
  needs:
    - job: get-features
      artifacts: true
  rules:
    - if: '$ENABLE_KARATE == "true" ||  $ENABLE_KARATE == "TRUE"'
      when: on_success

load-tests:
  <<: *tags_rlt
  image: adoptopenjdk:11-jdk-openj9-bionic
  stage: load-tests
  allow_failure: true
  variables:
    TEST_CONFIGURATION_PATH: "./src/test/java/test-plan.json"
    http_proxy: "http://${PROXY_HOST}:${PROXY_PORT}"
    https_proxy: "http://${PROXY_HOST}:${PROXY_PORT}"
    no_proxy: "127.0.0.1,localhost"
    GRADLE_OPTS: "-Dhttp.proxyHost=${PROXY_HOST} -Dhttp.proxyPort=${PROXY_PORT} -Dhttps.proxyHost=${PROXY_HOST} -Dhttps.proxyPort=${PROXY_PORT} -DnonProxyHosts=${no_proxy}"
  script:
    - source config/api-env/Common
    - ./gradlew --no-daemon gatling -Dkarate.env=$ENV
  artifacts:
    expire_in: 12 hrs
    paths:
      - build
    when: always
  needs:
    - job: get-features
      artifacts: true
  rules:
    - if: '$ENABLE_GATLING == "true" ||  $ENABLE_GATLING == "TRUE"'
      when: on_success

send-report-functional-tests:
  <<: *tags_rlt
  image: node:10-alpine
  stage: send-report
  variables:
    JIRA_XRAY_HOST: jira.dt.renault.com
    XC_DEFAULT_TEST_PLAN: $TEST_PLAN_JIRA_KEY
    XC_FEATURES_DOWNLOAD_DIRECTORY: "../../src/test/java/com/renault"
    XC_FEATURES_REPORT_DIRECTORY: "../../build/surefire-reports"
    XC_MERGED_REPORT_DIRECTORY: "../../build/merged"
    XC_TEST_ENVIRONMENT: $ENV
    XC_TEST_LABELS: "${API_NAME},integration"
  environment:
    name: $API_NAME/$ENV/integration
    url: https://$IRN.gitlab-pages.dt.renault.com/-/tda-blackbox-tests-api/-/jobs/$CI_JOB_ID/artifacts/report/cucumber/overview-features.html
  script:
    - mkdir -p ./report/cucumber && cp -R ./build/cucumber-html-reports/* ./report/cucumber
    - apk add -Uuv curl
    - cd tools/xray-connector
    - curl -u${ARTIFACTORY_USER}:${ARTIFACTORY_TOKEN} "https://artifactory.dt.renault.com/artifactory/api/npm/npm-renault/auth/rd" > .npmrc
    - npm install
    - npm run xc:build-report
    - npm run xc:send-report
  artifacts:
    when: always
    expire_in: 2 week
    paths:
      - report/cucumber
  needs:
    - job: functional-tests
      artifacts: true
  rules:
    - if: '$ENABLE_KARATE == "true" ||  $ENABLE_KARATE == "TRUE"'
      when: on_success

send-report-load-tests:
  <<: *tags_rlt
  image: node:10-alpine
  stage: send-report
  variables:
    JIRA_XRAY_HOST: jira.dt.renault.com
    XC_DEFAULT_TEST_PLAN: $TEST_PLAN_JIRA_KEY
    XC_FEATURES_DOWNLOAD_DIRECTORY: "../../src/test/java/com/renault"
    XC_FEATURES_REPORT_DIRECTORY: "../../build/reports/gatling"
    XC_MERGED_REPORT_DIRECTORY: "../../build/reports/gatling/merged"
    XC_GATLING_REPORTS_DIRECTORY: "../../build/reports/gatling"
    XC_GATLING_SIMULATION: "GenericTest"
    XC_TEST_PLAN_FILE: "../../src/test/java/test-plan.json"
    XC_GATLING_REPORT_URL: https://$IRN.gitlab-pages.dt.renault.com/-/tda-blackbox-tests-api/-/jobs/$CI_JOB_ID/artifacts/report/gatling/index.html
    XC_TEST_ENVIRONMENT: $ENV
    XC_TEST_LABELS: "${API_NAME},performance"
  environment:
    name: $API_NAME/$ENV/performance
    url: https://$IRN.gitlab-pages.dt.renault.com/-/tda-blackbox-tests-api/-/jobs/$CI_JOB_ID/artifacts/report/gatling/index.html
  script:
    - mkdir -p ./report/gatling && cp -R ./build/reports/gatling/generictest*/* ./report/gatling
    - apk add -Uuv curl
    - cd tools/xray-connector
    - curl -u${ARTIFACTORY_USER}:${ARTIFACTORY_TOKEN} "https://artifactory.dt.renault.com/artifactory/api/npm/npm-renault/auth/rd" > .npmrc
    - npm install
    - npm run xc:build-gatling-report
    - npm run xc:send-report
  artifacts:
    when: always
    expire_in: 2 week
    paths:
      - report/gatling
  needs:
    - job: load-tests
      artifacts: true
  rules:
    - if: '$ENABLE_GATLING == "true" ||  $ENABLE_GATLING == "TRUE"'
      when: on_success